### ISSUE TITLE
.gitattributes Globs Don't Work In Nested Directories

### ISSUE THREAD

**Issue by benrob0329** [Kentzo/git-archive-all#78] opened 2020-01-31 18:15 UTC
Version: Both 1.17.1 (Fedora 31 Repositories) and 1.20.0 (Master)

Example `.gitattributes`:
```
**/src export-ignore
/**/*.sh export-ignore
/.luacheckrc export-ignore
/.lua-format export-ignore
/.gitignore export-ignore
/palette.png export-ignore
/CONTRIBUTING.md export-ignore
```
Repository: https://gitlab.com/benrob0329/ikea

Resulting archive includes `src` directories, although the `*.sh` files in the root directory have been cleaned up.

**Comment by Kentzo** [comment] 2020-02-09 16:40
Was able to reproduce.

The script relies on `git check-attr` to verify file attributes. However, attributes set for the directories are not propagated onto contained files.

**Comment by Kentzo** [comment] 2020-02-09 18:12
@benrob0329 Please check the issue-78 branch.

**Comment by benrob0329** [comment] 2020-02-10 23:16
That seems to work as expected.

**Comment by Kentzo** [comment] 2020-02-13 19:03
Fixed in 1.21

**Closed** 2020-02-13 19:03 UTC

**Comment by Warr1024** [comment] 2020-02-15 15:46
Looks like it's actually only fixed for `export-ignore` but _still broken_ for `export-subst`.

Example repo: https://gitlab.com/sztest/nodecore

The affected file should be in `mods/nc_api/version.lua`.

**Comment by Kentzo** [comment] 2020-02-15 15:48
`export-subst` is not currently supported. Could you create a separate issue?
