### ISSUE TITLE
Excluding directories does not work like git archive

### ISSUE THREAD

**Issue by Gustry** [Kentzo/git-archive-all#79] opened 2020-02-01 15:57 UTC
I have this `.gitattributes` file as an example:

```
.github export-ignore
Makefile export-ignore
test export-ignore
```

`.github` and `test` are folders.

If I run:
* ` git archive --format zip --prefix lizmap/ HEAD -o lizmap.zip`, it works well. The `.github` folder is skipped from the archive.
* `git-archive-all --prefix=lizmap/ lizmap.zip` does not work. I have `.github`, `test` etc in the archive. 

In both cases, the makefile is skipped because it's a file.

I think the behavior should be the same.
What is the syntax to exclude directories with git-archive-all?

Thanks

**Comment by rubenwardy** [comment] 2020-02-03 13:49
Duplicate of #78

**Comment by Kentzo** [comment] 2020-02-09 18:13
@Gustry Please check the issue-78 branch.

**Closed** 2020-02-09 18:13 UTC
